// Hand-curated "the story of…" / "the … chapter" map for the quick-find: things an
// operator names that aren't in the verse text ("prodigal son" never appears in the KJV).
// Matched in the renderer — static data, no IPC. Titles are display strings; aliases are
// extra ways people say it. Ranges are validated against the bundled KJV in passages.test.
import { norm, textSignals } from '../search/fuzzy'
import { parseVerseQuery } from '../search/verseScore'
import { canonicalBookIndex } from './books'

export interface Passage { title: string; aliases: string[]; book: string; ch: number; from: number; to: number }

const P = (title: string, book: string, ch: number, from: number, to: number, ...aliases: string[]): Passage =>
  ({ title, aliases, book, ch, from, to })

export const PASSAGES: Passage[] = [
  // --- Genesis / Pentateuch
  P('Creation', 'Genesis', 1, 1, 31, 'in the beginning', 'seven days', 'creation story'),
  P('Adam and Eve', 'Genesis', 2, 4, 25, 'garden of eden', 'eden'),
  P('The Fall', 'Genesis', 3, 1, 24, 'serpent', 'forbidden fruit', 'fall of man'),
  P('Cain and Abel', 'Genesis', 4, 1, 16, 'my brothers keeper'),
  P('Noah and the Flood', 'Genesis', 6, 9, 22, 'ark', 'flood', 'noahs ark'),
  P('The Rainbow Covenant', 'Genesis', 9, 8, 17, 'rainbow'),
  P('Tower of Babel', 'Genesis', 11, 1, 9, 'babel'),
  P('The Call of Abram', 'Genesis', 12, 1, 9, 'abraham called', 'go from your country'),
  P('Abraham Offers Isaac', 'Genesis', 22, 1, 19, 'sacrifice of isaac', 'binding of isaac', 'mount moriah'),
  P('Jacob\'s Ladder', 'Genesis', 28, 10, 22, 'jacobs dream', 'bethel'),
  P('Jacob Wrestles with God', 'Genesis', 32, 22, 32, 'jacob wrestles', 'peniel'),
  P('Joseph\'s Coat', 'Genesis', 37, 1, 36, 'coat of many colours', 'coat of many colors', 'joseph sold'),
  P('Joseph Reveals Himself', 'Genesis', 45, 1, 15, 'joseph brothers', 'you meant evil against me'),
  P('Moses and the Burning Bush', 'Exodus', 3, 1, 22, 'burning bush', 'i am that i am'),
  P('The Passover', 'Exodus', 12, 1, 28, 'passover lamb'),
  P('Crossing the Red Sea', 'Exodus', 14, 10, 31, 'red sea', 'parting of the sea'),
  P('Manna from Heaven', 'Exodus', 16, 1, 36, 'manna'),
  P('The Ten Commandments', 'Exodus', 20, 1, 17, 'ten commandments', 'decalogue', 'commandments'),
  P('The Golden Calf', 'Exodus', 32, 1, 35, 'golden calf'),
  P('The Priestly Blessing', 'Numbers', 6, 22, 27, 'the lord bless thee and keep thee', 'aaronic blessing'),
  P('The Bronze Serpent', 'Numbers', 21, 4, 9, 'brazen serpent', 'serpent on a pole'),
  P('Balaam\'s Donkey', 'Numbers', 22, 21, 35, 'balaam', 'talking donkey'),
  P('The Shema', 'Deuteronomy', 6, 4, 9, 'hear o israel', 'shema'),
  P('Choose Life', 'Deuteronomy', 30, 11, 20, 'choose life'),
  // --- History
  P('Be Strong and Courageous', 'Joshua', 1, 1, 9, 'be strong and of a good courage'),
  P('Rahab and the Spies', 'Joshua', 2, 1, 24, 'rahab'),
  P('The Walls of Jericho', 'Joshua', 6, 1, 27, 'jericho', 'walls fell'),
  P('As for Me and My House', 'Joshua', 24, 14, 15, 'as for me and my house'),
  P('Gideon\'s Fleece', 'Judges', 6, 36, 40, 'gideon fleece'),
  P('Gideon\'s Three Hundred', 'Judges', 7, 1, 25, 'gideon 300', 'three hundred men'),
  P('Samson and Delilah', 'Judges', 16, 4, 31, 'samson', 'delilah'),
  P('Ruth and Naomi', 'Ruth', 1, 1, 22, 'whither thou goest', 'ruth'),
  P('Hannah\'s Prayer', '1 Samuel', 1, 9, 28, 'hannah'),
  P('Samuel Called', '1 Samuel', 3, 1, 21, 'speak lord for thy servant heareth', 'samuel hears god'),
  P('David Anointed', '1 Samuel', 16, 1, 13, 'man looketh on the outward appearance', 'samuel anoints david'),
  P('David and Goliath', '1 Samuel', 17, 1, 58, 'goliath', 'five smooth stones'),
  P('David and Jonathan', '1 Samuel', 18, 1, 4, 'jonathan covenant'),
  P('David and Bathsheba', '2 Samuel', 11, 1, 27, 'bathsheba', 'uriah'),
  P('Nathan Confronts David', '2 Samuel', 12, 1, 14, 'thou art the man', 'nathan'),
  P('Solomon Asks for Wisdom', '1 Kings', 3, 5, 15, 'solomon wisdom', 'an understanding heart'),
  P('Solomon\'s Judgment', '1 Kings', 3, 16, 28, 'divide the child', 'two mothers'),
  P('Elijah and the Ravens', '1 Kings', 17, 1, 7, 'ravens', 'brook cherith'),
  P('Elijah and the Widow of Zarephath', '1 Kings', 17, 8, 24, 'zarephath', 'widows oil', 'cruse of oil'),
  P('Elijah on Mount Carmel', '1 Kings', 18, 20, 40, 'prophets of baal', 'mount carmel', 'fire from heaven'),
  P('The Still Small Voice', '1 Kings', 19, 9, 18, 'still small voice', 'elijah cave'),
  P('Elijah Taken Up', '2 Kings', 2, 1, 14, 'chariot of fire', 'elijah whirlwind', 'elisha mantle'),
  P('Naaman Healed', '2 Kings', 5, 1, 19, 'naaman', 'dip seven times', 'leprosy jordan'),
  P('The Axe Head Floats', '2 Kings', 6, 1, 7, 'axe head'),
  P('Horses and Chariots of Fire', '2 Kings', 6, 8, 23, 'open his eyes', 'more with us'),
  P('Hezekiah\'s Prayer', '2 Kings', 19, 14, 19, 'hezekiah'),
  P('Jabez', '1 Chronicles', 4, 9, 10, 'prayer of jabez'),
  P('If My People', '2 Chronicles', 7, 11, 22, 'if my people which are called by my name', 'heal their land'),
  P('Nehemiah Rebuilds the Wall', 'Nehemiah', 2, 11, 20, 'rebuild the wall'),
  P('Esther: For Such a Time as This', 'Esther', 4, 1, 17, 'for such a time as this', 'esther'),
  P('Job\'s Trials', 'Job', 1, 1, 22, 'the lord gave and the lord hath taken away', 'job'),
  P('I Know That My Redeemer Liveth', 'Job', 19, 23, 27, 'my redeemer liveth'),
  P('God Answers Job', 'Job', 38, 1, 41, 'where wast thou', 'out of the whirlwind'),
  // --- Psalms / Wisdom
  P('Psalm 1: Blessed Is the Man', 'Psalm', 1, 1, 6, 'blessed is the man', 'tree planted by the rivers'),
  P('Psalm 8: What Is Man', 'Psalm', 8, 1, 9, 'what is man'),
  P('Psalm 19: The Heavens Declare', 'Psalm', 19, 1, 14, 'heavens declare'),
  P('Psalm 22: My God, Why Hast Thou Forsaken Me', 'Psalm', 22, 1, 31, 'forsaken me'),
  P('Psalm 23: The Lord Is My Shepherd', 'Psalm', 23, 1, 6, 'shepherd psalm', 'valley of the shadow of death'),
  P('Psalm 24: The King of Glory', 'Psalm', 24, 1, 10, 'king of glory', 'lift up your heads'),
  P('Psalm 27: The Lord Is My Light', 'Psalm', 27, 1, 14, 'my light and my salvation'),
  P('Psalm 32: Blessed Is He Whose Transgression Is Forgiven', 'Psalm', 32, 1, 11, 'transgression forgiven'),
  P('Psalm 34: Taste and See', 'Psalm', 34, 1, 22, 'taste and see'),
  P('Psalm 37: Fret Not', 'Psalm', 37, 1, 11, 'fret not', 'delight thyself in the lord'),
  P('Psalm 40: He Brought Me Up Out of the Pit', 'Psalm', 40, 1, 5, 'horrible pit', 'new song'),
  P('Psalm 42: As the Deer', 'Psalm', 42, 1, 11, 'as the hart panteth', 'as the deer'),
  P('Psalm 46: God Is Our Refuge', 'Psalm', 46, 1, 11, 'be still and know', 'refuge and strength'),
  P('Psalm 51: Create in Me a Clean Heart', 'Psalm', 51, 1, 19, 'clean heart', 'have mercy upon me o god', 'davids repentance'),
  P('Psalm 84: How Amiable Are Thy Tabernacles', 'Psalm', 84, 1, 12, 'better is a day in thy courts'),
  P('Psalm 90: Teach Us to Number Our Days', 'Psalm', 90, 1, 17, 'number our days'),
  P('Psalm 91: He That Dwelleth in the Secret Place', 'Psalm', 91, 1, 16, 'secret place of the most high', 'shadow of the almighty'),
  P('Psalm 100: Make a Joyful Noise', 'Psalm', 100, 1, 5, 'joyful noise', 'enter into his gates'),
  P('Psalm 103: Bless the Lord, O My Soul', 'Psalm', 103, 1, 22, 'bless the lord o my soul', 'as far as the east is from the west'),
  P('Psalm 118: This Is the Day', 'Psalm', 118, 19, 29, 'this is the day which the lord hath made'),
  P('Psalm 119: Thy Word Is a Lamp', 'Psalm', 119, 105, 112, 'lamp unto my feet'),
  P('Psalm 121: I Will Lift Up Mine Eyes', 'Psalm', 121, 1, 8, 'lift up mine eyes unto the hills', 'my help cometh'),
  P('Psalm 127: Except the Lord Build the House', 'Psalm', 127, 1, 5, 'except the lord build the house', 'children are an heritage'),
  P('Psalm 133: How Good and How Pleasant', 'Psalm', 133, 1, 3, 'brethren dwell together in unity'),
  P('Psalm 139: Fearfully and Wonderfully Made', 'Psalm', 139, 1, 24, 'fearfully and wonderfully made', 'search me o god'),
  P('Psalm 150: Praise Ye the Lord', 'Psalm', 150, 1, 6, 'let every thing that hath breath'),
  P('Trust in the Lord with All Thine Heart', 'Proverbs', 3, 1, 12, 'trust in the lord', 'lean not unto thine own understanding'),
  P('The Virtuous Woman', 'Proverbs', 31, 10, 31, 'proverbs 31 woman', 'virtuous woman', 'wife of noble character'),
  P('A Time for Everything', 'Ecclesiastes', 3, 1, 8, 'to every thing there is a season', 'a time to be born'),
  P('Remember Thy Creator', 'Ecclesiastes', 12, 1, 14, 'remember now thy creator', 'fear god and keep his commandments'),
  // --- Prophets
  P('Isaiah\'s Call: Here Am I', 'Isaiah', 6, 1, 13, 'here am i send me', 'holy holy holy', 'isaiah vision'),
  P('Unto Us a Child Is Born', 'Isaiah', 9, 1, 7, 'unto us a child is born', 'prince of peace', 'wonderful counsellor'),
  P('They That Wait upon the Lord', 'Isaiah', 40, 27, 31, 'wait upon the lord', 'mount up with wings as eagles', 'comfort ye'),
  P('Fear Not, I Am with Thee', 'Isaiah', 41, 8, 13, 'fear thou not for i am with thee'),
  P('When Thou Passest Through the Waters', 'Isaiah', 43, 1, 7, 'through the waters', 'called thee by thy name'),
  P('The Suffering Servant', 'Isaiah', 53, 1, 12, 'suffering servant', 'by his stripes', 'wounded for our transgressions'),
  P('Come, Everyone That Thirsteth', 'Isaiah', 55, 1, 13, 'my ways are not your ways', 'ho every one that thirsteth'),
  P('The Spirit of the Lord Is upon Me', 'Isaiah', 61, 1, 3, 'beauty for ashes', 'spirit of the lord god is upon me'),
  P('Jeremiah\'s Call', 'Jeremiah', 1, 4, 10, 'before i formed thee'),
  P('The Potter and the Clay', 'Jeremiah', 18, 1, 12, 'potter', 'clay'),
  P('Plans to Prosper You', 'Jeremiah', 29, 10, 14, 'thoughts of peace', 'plans to prosper', 'expected end', 'jeremiah 29 11'),
  P('The New Covenant', 'Jeremiah', 31, 31, 34, 'new covenant', 'law in their inward parts'),
  P('Great Is Thy Faithfulness', 'Lamentations', 3, 22, 26, 'new every morning', 'great is thy faithfulness'),
  P('Valley of Dry Bones', 'Ezekiel', 37, 1, 14, 'dry bones'),
  P('A New Heart', 'Ezekiel', 36, 24, 28, 'heart of stone', 'heart of flesh'),
  P('The Fiery Furnace', 'Daniel', 3, 1, 30, 'shadrach meshach abednego', 'furnace', 'three hebrew children'),
  P('The Writing on the Wall', 'Daniel', 5, 1, 31, 'mene mene tekel', 'belshazzar', 'handwriting on the wall'),
  P('Daniel in the Lions\' Den', 'Daniel', 6, 1, 28, 'lions den', 'daniel lions'),
  P('Jonah and the Great Fish', 'Jonah', 1, 1, 17, 'jonah', 'whale', 'great fish'),
  P('Jonah\'s Prayer', 'Jonah', 2, 1, 10, 'belly of the fish'),
  P('What Doth the Lord Require', 'Micah', 6, 6, 8, 'do justly love mercy walk humbly'),
  P('The Just Shall Live by Faith', 'Habakkuk', 2, 1, 4, 'write the vision', 'just shall live by his faith'),
  P('Bring Ye All the Tithes', 'Malachi', 3, 6, 12, 'tithes', 'windows of heaven', 'storehouse'),
  // --- Gospels: birth & early
  P('The Annunciation', 'Luke', 1, 26, 38, 'gabriel mary', 'annunciation', 'hail thou that art highly favoured'),
  P('The Magnificat', 'Luke', 1, 46, 55, 'my soul doth magnify the lord', 'marys song'),
  P('The Nativity', 'Luke', 2, 1, 20, 'birth of jesus', 'christmas story', 'manger', 'shepherds', 'no room in the inn'),
  P('The Wise Men', 'Matthew', 2, 1, 12, 'magi', 'wise men', 'star in the east', 'gold frankincense myrrh'),
  P('Flight into Egypt', 'Matthew', 2, 13, 23, 'flight to egypt', 'herod slaughter'),
  P('The Boy Jesus in the Temple', 'Luke', 2, 41, 52, 'about my fathers business', 'jesus age twelve'),
  P('The Baptism of Jesus', 'Matthew', 3, 13, 17, 'baptism', 'this is my beloved son'),
  P('The Temptation of Jesus', 'Matthew', 4, 1, 11, 'temptation', 'wilderness forty days', 'man shall not live by bread alone'),
  P('Calling of the First Disciples', 'Matthew', 4, 18, 22, 'fishers of men', 'follow me'),
  P('Water into Wine', 'John', 2, 1, 11, 'wedding at cana', 'cana', 'first miracle'),
  P('Jesus Cleanses the Temple', 'John', 2, 13, 22, 'moneychangers', 'den of thieves', 'cleansing of the temple'),
  P('Nicodemus: Born Again', 'John', 3, 1, 21, 'born again', 'nicodemus', 'john 3 16', 'god so loved the world'),
  P('The Woman at the Well', 'John', 4, 1, 42, 'samaritan woman', 'living water', 'woman at the well'),
  P('The Pool of Bethesda', 'John', 5, 1, 15, 'bethesda', 'wilt thou be made whole', 'take up thy bed'),
  // --- Sermon on the Mount
  P('The Sermon on the Mount', 'Matthew', 5, 1, 48, 'sermon on the mount'),
  P('The Beatitudes', 'Matthew', 5, 1, 12, 'beatitudes', 'blessed are the poor in spirit', 'blessed are'),
  P('Salt and Light', 'Matthew', 5, 13, 16, 'salt of the earth', 'light of the world', 'city on a hill', 'let your light so shine'),
  P('Love Your Enemies', 'Matthew', 5, 38, 48, 'turn the other cheek', 'love your enemies', 'go the extra mile'),
  P('The Lord\'s Prayer', 'Matthew', 6, 9, 15, 'lords prayer', 'our father', 'our father which art in heaven', 'the lord prayer'),
  P('Treasures in Heaven', 'Matthew', 6, 19, 24, 'lay up treasures in heaven', 'no man can serve two masters', 'mammon'),
  P('Consider the Lilies', 'Matthew', 6, 25, 34, 'take no thought', 'lilies of the field', 'seek ye first', 'do not worry'),
  P('Judge Not', 'Matthew', 7, 1, 6, 'judge not', 'mote and beam', 'speck and plank'),
  P('Ask, Seek, Knock', 'Matthew', 7, 7, 12, 'ask and it shall be given', 'seek and ye shall find', 'golden rule'),
  P('The Narrow Gate', 'Matthew', 7, 13, 14, 'strait gate', 'narrow way'),
  P('Wise and Foolish Builders', 'Matthew', 7, 24, 29, 'house on the rock', 'house upon the sand', 'wise man built his house'),
  // --- Miracles
  P('The Centurion\'s Servant', 'Matthew', 8, 5, 13, 'centurion', 'speak the word only'),
  P('Jesus Calms the Storm', 'Mark', 4, 35, 41, 'calms the storm', 'peace be still', 'stilling the storm', 'storm on the sea'),
  P('The Gadarene Demoniac', 'Mark', 5, 1, 20, 'legion', 'swine', 'demoniac', 'gadarene', 'gerasene'),
  P('Jairus\' Daughter', 'Mark', 5, 21, 43, 'jairus', 'talitha cumi', 'damsel arise'),
  P('The Woman with the Issue of Blood', 'Mark', 5, 25, 34, 'hem of his garment', 'issue of blood', 'touched his garment'),
  P('Feeding the Five Thousand', 'John', 6, 1, 14, 'five loaves and two fishes', 'feeding of the 5000', 'five thousand', 'loaves and fishes'),
  P('Jesus Walks on Water', 'Matthew', 14, 22, 33, 'walks on water', 'peter walks on water', 'o thou of little faith'),
  P('The Canaanite Woman\'s Faith', 'Matthew', 15, 21, 28, 'syrophenician woman', 'crumbs from the masters table'),
  P('The Transfiguration', 'Matthew', 17, 1, 9, 'transfiguration', 'mount of transfiguration', 'moses and elias'),
  P('Healing of the Blind Man', 'John', 9, 1, 41, 'born blind', 'whereas i was blind now i see', 'pool of siloam'),
  P('Bartimaeus', 'Mark', 10, 46, 52, 'blind bartimaeus', 'son of david have mercy on me'),
  P('The Ten Lepers', 'Luke', 17, 11, 19, 'ten lepers', 'one returned to give thanks'),
  P('Raising of Lazarus', 'John', 11, 1, 44, 'lazarus', 'lazarus come forth', 'i am the resurrection and the life', 'jesus wept'),
  P('Peter\'s Great Catch', 'Luke', 5, 1, 11, 'launch out into the deep', 'miraculous catch of fish'),
  P('The Widow of Nain', 'Luke', 7, 11, 17, 'nain', 'widows son raised'),
  P('The Man Through the Roof', 'Mark', 2, 1, 12, 'paralytic', 'let down through the roof', 'thy sins be forgiven thee'),
  P('The Withered Hand', 'Mark', 3, 1, 6, 'withered hand', 'lawful on the sabbath'),
  // --- Parables
  P('The Sower', 'Matthew', 13, 1, 23, 'parable of the sower', 'sower', 'seed fell by the wayside', 'good ground'),
  P('The Wheat and the Tares', 'Matthew', 13, 24, 30, 'tares', 'wheat and tares', 'parable of the weeds', 'parable of the tares'),
  P('The Mustard Seed', 'Matthew', 13, 31, 32, 'mustard seed', 'parable of the mustard seed'),
  P('The Hidden Treasure and the Pearl', 'Matthew', 13, 44, 46, 'pearl of great price', 'treasure hid in a field', 'parable of the pearl', 'parable of the hidden treasure'),
  P('The Unmerciful Servant', 'Matthew', 18, 21, 35, 'seventy times seven', 'unforgiving servant', 'ten thousand talents', 'parable of the unmerciful servant'),
  P('The Labourers in the Vineyard', 'Matthew', 20, 1, 16, 'labourers in the vineyard', 'workers in the vineyard', 'penny a day', 'parable of the labourers'),
  P('The Wicked Husbandmen', 'Matthew', 21, 33, 46, 'wicked husbandmen', 'tenants', 'stone which the builders rejected', 'parable of the wicked husbandmen', 'parable of the tenants'),
  P('The Wedding Feast', 'Matthew', 22, 1, 14, 'wedding garment', 'marriage feast', 'many are called but few are chosen', 'parable of the wedding feast'),
  P('The Ten Virgins', 'Matthew', 25, 1, 13, 'ten virgins', 'wise and foolish virgins', 'lamps oil bridegroom', 'parable of the ten virgins'),
  P('The Talents', 'Matthew', 25, 14, 30, 'parable of the talents', 'talents', 'well done thou good and faithful servant'),
  P('The Sheep and the Goats', 'Matthew', 25, 31, 46, 'sheep and goats', 'least of these', 'inasmuch as ye have done it', 'parable of the sheep and the goats'),
  P('The Good Samaritan', 'Luke', 10, 25, 37, 'good samaritan', 'who is my neighbour', 'samaritan', 'parable of the good samaritan'),
  P('Mary and Martha', 'Luke', 10, 38, 42, 'mary and martha', 'martha', 'one thing is needful'),
  P('The Friend at Midnight', 'Luke', 11, 5, 13, 'friend at midnight', 'importunity', 'parable of the friend at midnight'),
  P('The Rich Fool', 'Luke', 12, 13, 21, 'rich fool', 'bigger barns', 'thou fool this night', 'parable of the rich fool'),
  P('The Barren Fig Tree', 'Luke', 13, 6, 9, 'barren fig tree', 'parable of the barren fig tree'),
  P('The Great Supper', 'Luke', 14, 15, 24, 'great supper', 'compel them to come in', 'highways and hedges', 'parable of the great supper'),
  P('Counting the Cost', 'Luke', 14, 25, 35, 'count the cost', 'take up his cross'),
  P('The Lost Sheep', 'Luke', 15, 1, 7, 'lost sheep', 'ninety and nine', 'leave the ninety nine', 'parable of the lost sheep'),
  P('The Lost Coin', 'Luke', 15, 8, 10, 'lost coin', 'ten pieces of silver', 'parable of the lost coin'),
  P('The Prodigal Son', 'Luke', 15, 11, 32, 'prodigal son', 'prodigal', 'lost son', 'younger son', 'fatted calf', 'came to himself', 'parable of the prodigal son', 'parable of the lost son'),
  P('The Unjust Steward', 'Luke', 16, 1, 13, 'unjust steward', 'shrewd manager', 'parable of the unjust steward'),
  P('The Rich Man and Lazarus', 'Luke', 16, 19, 31, 'rich man and lazarus', 'dives', 'abrahams bosom', 'parable of the rich man and lazarus'),
  P('The Persistent Widow', 'Luke', 18, 1, 8, 'unjust judge', 'persistent widow', 'importunate widow', 'parable of the persistent widow', 'parable of the unjust judge'),
  P('The Pharisee and the Publican', 'Luke', 18, 9, 14, 'pharisee and the publican', 'god be merciful to me a sinner', 'tax collector', 'parable of the pharisee and the publican'),
  P('Zacchaeus', 'Luke', 19, 1, 10, 'zacchaeus', 'zaccheus', 'sycamore tree', 'wee little man'),
  P('The Pounds', 'Luke', 19, 11, 27, 'parable of the pounds', 'minas', 'occupy till i come'),
  P('The Good Shepherd', 'John', 10, 1, 18, 'good shepherd', 'i am the door', 'sheepfold'),
  P('The Vine and the Branches', 'John', 15, 1, 17, 'true vine', 'vine and branches', 'abide in me'),
  // --- Teaching moments
  P('Come unto Me', 'Matthew', 11, 25, 30, 'come unto me all ye that labour', 'my yoke is easy'),
  P('Peter\'s Confession', 'Matthew', 16, 13, 20, 'thou art the christ', 'upon this rock', 'who do men say that i am', 'caesarea philippi'),
  P('Take Up Your Cross', 'Matthew', 16, 21, 28, 'deny himself', 'take up his cross and follow me', 'what shall it profit a man'),
  P('The Greatest in the Kingdom', 'Matthew', 18, 1, 6, 'become as little children', 'millstone'),
  P('Jesus Blesses the Children', 'Mark', 10, 13, 16, 'suffer the little children', 'let the children come'),
  P('The Rich Young Ruler', 'Mark', 10, 17, 27, 'rich young ruler', 'eye of a needle', 'sell all that thou hast'),
  P('The Greatest Commandment', 'Matthew', 22, 34, 40, 'greatest commandment', 'love the lord thy god with all thy heart', 'love thy neighbour as thyself'),
  P('The Widow\'s Mite', 'Mark', 12, 41, 44, 'widows mite', 'two mites', 'widows offering'),
  P('Render unto Caesar', 'Matthew', 22, 15, 22, 'render unto caesar', 'tribute money'),
  P('The Woman Caught in Adultery', 'John', 8, 1, 11, 'cast the first stone', 'woman taken in adultery', 'go and sin no more'),
  P('I Am the Light of the World', 'John', 8, 12, 20, 'light of the world'),
  P('The Truth Shall Make You Free', 'John', 8, 31, 36, 'truth shall make you free'),
  P('The Bread of Life', 'John', 6, 25, 59, 'bread of life', 'i am the bread of life'),
  P('The Woman Who Anointed Jesus', 'Luke', 7, 36, 50, 'alabaster box', 'washed his feet with tears', 'sinful woman', 'her sins which are many are forgiven'),
  P('Mary Anoints Jesus', 'John', 12, 1, 8, 'spikenard', 'mary anoints', 'ointment'),
  P('The Woes to the Pharisees', 'Matthew', 23, 1, 39, 'woe unto you scribes and pharisees', 'whited sepulchres'),
  P('The Olivet Discourse', 'Matthew', 24, 1, 51, 'signs of the end', 'end times', 'olivet discourse', 'wars and rumours of wars'),
  // --- Passion week
  P('The Triumphal Entry', 'Matthew', 21, 1, 11, 'palm sunday', 'triumphal entry', 'hosanna', 'colt'),
  P('The Last Supper', 'Luke', 22, 7, 23, 'last supper', 'lords supper', 'this is my body', 'communion', 'upper room'),
  P('Jesus Washes the Disciples\' Feet', 'John', 13, 1, 17, 'washes feet', 'foot washing', 'towel and basin'),
  P('A New Commandment', 'John', 13, 31, 35, 'new commandment', 'love one another', 'by this shall all men know'),
  P('Let Not Your Heart Be Troubled', 'John', 14, 1, 14, 'in my fathers house are many mansions', 'i am the way the truth and the life', 'many mansions'),
  P('The Comforter Promised', 'John', 14, 15, 31, 'comforter', 'peace i leave with you', 'holy ghost teach you'),
  P('Jesus\' High Priestly Prayer', 'John', 17, 1, 26, 'high priestly prayer', 'that they all may be one'),
  P('Gethsemane', 'Matthew', 26, 36, 46, 'gethsemane', 'not my will but thine', 'let this cup pass', 'could ye not watch one hour'),
  P('The Betrayal and Arrest', 'Matthew', 26, 47, 56, 'judas kiss', 'betrayal', 'thirty pieces of silver', 'malchus ear'),
  P('Peter Denies Jesus', 'Luke', 22, 54, 62, 'peter denies', 'cock crow', 'denial', 'before the cock crow'),
  P('Jesus Before Pilate', 'John', 18, 28, 40, 'pilate', 'what is truth', 'barabbas', 'my kingdom is not of this world'),
  P('The Crucifixion', 'Luke', 23, 26, 49, 'crucifixion', 'calvary', 'golgotha', 'father forgive them', 'thief on the cross', 'it is finished', 'good friday'),
  P('The Seven Last Words', 'John', 19, 25, 30, 'woman behold thy son', 'i thirst', 'it is finished'),
  P('The Burial of Jesus', 'Matthew', 27, 57, 66, 'joseph of arimathaea', 'tomb', 'sealed the stone'),
  // --- Resurrection & after
  P('The Resurrection', 'Matthew', 28, 1, 10, 'resurrection', 'he is risen', 'empty tomb', 'easter', 'he is not here'),
  P('Mary Magdalene at the Tomb', 'John', 20, 11, 18, 'mary magdalene', 'rabboni', 'touch me not'),
  P('The Road to Emmaus', 'Luke', 24, 13, 35, 'emmaus', 'road to emmaus', 'did not our heart burn within us'),
  P('Doubting Thomas', 'John', 20, 24, 29, 'thomas', 'doubting thomas', 'my lord and my god', 'blessed are they that have not seen'),
  P('Feed My Sheep', 'John', 21, 15, 19, 'feed my sheep', 'lovest thou me', 'peter restored'),
  P('The Great Commission', 'Matthew', 28, 16, 20, 'great commission', 'go ye therefore', 'lo i am with you alway'),
  P('The Ascension', 'Acts', 1, 1, 11, 'ascension', 'ye shall receive power', 'taken up'),
  P('Pentecost', 'Acts', 2, 1, 21, 'pentecost', 'tongues of fire', 'rushing mighty wind', 'filled with the holy ghost'),
  P('Peter\'s Sermon at Pentecost', 'Acts', 2, 22, 41, 'repent and be baptized', 'three thousand souls'),
  P('The Early Church', 'Acts', 2, 42, 47, 'all things common', 'breaking of bread', 'fellowship'),
  P('The Lame Man at the Gate Beautiful', 'Acts', 3, 1, 10, 'silver and gold have i none', 'gate beautiful', 'rise up and walk'),
  P('Ananias and Sapphira', 'Acts', 5, 1, 11, 'ananias and sapphira', 'lied to the holy ghost'),
  P('Stephen\'s Martyrdom', 'Acts', 7, 54, 60, 'stephen stoned', 'stephen', 'lay not this sin to their charge'),
  P('Philip and the Ethiopian', 'Acts', 8, 26, 40, 'ethiopian eunuch', 'philip', 'understandest thou what thou readest'),
  P('The Road to Damascus', 'Acts', 9, 1, 19, 'road to damascus', 'damascus', 'saul conversion', 'why persecutest thou me', 'scales fell from his eyes'),
  P('Peter\'s Vision', 'Acts', 10, 9, 23, 'peters vision', 'sheet let down', 'what god hath cleansed', 'cornelius'),
  P('Peter Freed from Prison', 'Acts', 12, 1, 19, 'peter prison angel', 'rhoda', 'chains fell off'),
  P('Paul and Silas in Prison', 'Acts', 16, 16, 40, 'paul and silas', 'philippian jailer', 'what must i do to be saved', 'prison doors opened', 'midnight sang praises'),
  P('Paul at Mars Hill', 'Acts', 17, 16, 34, 'mars hill', 'areopagus', 'unknown god', 'in him we live and move'),
  P('Paul\'s Shipwreck', 'Acts', 27, 13, 44, 'shipwreck', 'paul shipwreck', 'malta', 'melita'),
  // --- Epistles
  P('The Righteous Shall Live by Faith', 'Romans', 1, 16, 17, 'not ashamed of the gospel', 'just shall live by faith'),
  P('All Have Sinned', 'Romans', 3, 21, 26, 'all have sinned', 'come short of the glory of god', 'justified freely'),
  P('Justified by Faith', 'Romans', 5, 1, 11, 'peace with god', 'while we were yet sinners', 'god commendeth his love'),
  P('Dead to Sin, Alive in Christ', 'Romans', 6, 1, 14, 'baptized into his death', 'newness of life', 'dead to sin'),
  P('The Wages of Sin', 'Romans', 6, 15, 23, 'wages of sin is death', 'gift of god is eternal life'),
  P('No Condemnation', 'Romans', 8, 1, 17, 'no condemnation', 'walk not after the flesh', 'abba father'),
  P('All Things Work Together', 'Romans', 8, 18, 30, 'all things work together for good', 'groanings which cannot be uttered', 'predestinate'),
  P('More Than Conquerors', 'Romans', 8, 31, 39, 'more than conquerors', 'if god be for us', 'nothing shall separate us'),
  P('Confess with Thy Mouth', 'Romans', 10, 8, 17, 'confess with thy mouth', 'whosoever shall call upon the name of the lord', 'faith cometh by hearing', 'how beautiful are the feet'),
  P('A Living Sacrifice', 'Romans', 12, 1, 8, 'living sacrifice', 'be not conformed to this world', 'renewing of your mind'),
  P('Love Without Hypocrisy', 'Romans', 12, 9, 21, 'overcome evil with good', 'bless them which persecute you', 'heap coals of fire'),
  P('The Message of the Cross', '1 Corinthians', 1, 18, 31, 'foolishness of god', 'preaching of the cross', 'not many wise men'),
  P('Your Body Is a Temple', '1 Corinthians', 6, 12, 20, 'temple of the holy ghost', 'bought with a price'),
  P('The Lord\'s Supper Instituted', '1 Corinthians', 11, 23, 34, 'as often as ye eat this bread', 'this do in remembrance of me', 'communion'),
  P('One Body, Many Members', '1 Corinthians', 12, 12, 31, 'body of christ', 'many members', 'spiritual gifts'),
  P('The Love Chapter', '1 Corinthians', 13, 1, 13, 'love chapter', 'charity suffereth long', 'love is patient', 'faith hope charity', 'faith hope love', 'though i speak with the tongues'),
  P('The Resurrection Chapter', '1 Corinthians', 15, 1, 58, 'resurrection chapter', 'o death where is thy sting', 'twinkling of an eye', 'last trump', 'be ye stedfast unmoveable'),
  P('Treasure in Earthen Vessels', '2 Corinthians', 4, 7, 18, 'earthen vessels', 'light affliction', 'things which are not seen'),
  P('A New Creature', '2 Corinthians', 5, 14, 21, 'new creature', 'ministry of reconciliation', 'ambassadors for christ', 'made him to be sin'),
  P('Cheerful Giver', '2 Corinthians', 9, 6, 15, 'cheerful giver', 'soweth sparingly', 'unspeakable gift'),
  P('My Grace Is Sufficient', '2 Corinthians', 12, 7, 10, 'thorn in the flesh', 'my grace is sufficient', 'strength made perfect in weakness'),
  P('Crucified with Christ', 'Galatians', 2, 15, 21, 'crucified with christ', 'nevertheless i live'),
  P('The Fruit of the Spirit', 'Galatians', 5, 16, 26, 'fruit of the spirit', 'works of the flesh', 'walk in the spirit'),
  P('Bear One Another\'s Burdens', 'Galatians', 6, 1, 10, 'bear ye one anothers burdens', 'whatsoever a man soweth', 'be not weary in well doing'),
  P('Saved by Grace', 'Ephesians', 2, 1, 10, 'by grace are ye saved', 'not of works', 'his workmanship'),
  P('One in Christ', 'Ephesians', 2, 11, 22, 'middle wall of partition', 'no more strangers', 'chief corner stone'),
  P('Unity in the Body', 'Ephesians', 4, 1, 16, 'one lord one faith one baptism', 'unity of the spirit', 'speaking the truth in love'),
  P('The New Man', 'Ephesians', 4, 17, 32, 'put on the new man', 'be ye kind one to another', 'let not the sun go down upon your wrath'),
  P('Husbands and Wives', 'Ephesians', 5, 22, 33, 'husbands love your wives', 'wives submit', 'marriage', 'two shall be one flesh'),
  P('The Armour of God', 'Ephesians', 6, 10, 20, 'armour of god', 'armor of god', 'whole armour', 'sword of the spirit', 'wiles of the devil', 'principalities and powers'),
  P('The Christ Hymn', 'Philippians', 2, 1, 11, 'let this mind be in you', 'every knee should bow', 'made himself of no reputation', 'kenosis'),
  P('Press Toward the Mark', 'Philippians', 3, 7, 14, 'press toward the mark', 'count all things but loss', 'forgetting those things which are behind'),
  P('Rejoice in the Lord Alway', 'Philippians', 4, 4, 9, 'rejoice in the lord alway', 'be careful for nothing', 'peace of god which passeth all understanding', 'whatsoever things are true'),
  P('I Can Do All Things', 'Philippians', 4, 10, 20, 'i can do all things through christ', 'my god shall supply all your need', 'content'),
  P('The Supremacy of Christ', 'Colossians', 1, 15, 23, 'image of the invisible god', 'firstborn of every creature', 'by him all things consist'),
  P('Set Your Affection on Things Above', 'Colossians', 3, 1, 17, 'things above', 'put on therefore', 'let the peace of god rule', 'whatsoever ye do in word or deed'),
  P('The Coming of the Lord', '1 Thessalonians', 4, 13, 18, 'caught up', 'rapture', 'dead in christ shall rise', 'trump of god', 'comfort one another with these words'),
  P('Rejoice Evermore, Pray Without Ceasing', '1 Thessalonians', 5, 12, 24, 'pray without ceasing', 'in every thing give thanks', 'quench not the spirit'),
  P('Fight the Good Fight', '1 Timothy', 6, 6, 19, 'godliness with contentment', 'love of money is the root of all evil', 'fight the good fight of faith'),
  P('Spirit of Power, Love, and a Sound Mind', '2 Timothy', 1, 3, 12, 'spirit of fear', 'sound mind', 'i know whom i have believed'),
  P('All Scripture Is Given by Inspiration', '2 Timothy', 3, 10, 17, 'all scripture is given by inspiration of god', 'perilous times', 'inspiration of god'),
  P('I Have Fought a Good Fight', '2 Timothy', 4, 1, 8, 'i have fought a good fight', 'finished my course', 'crown of righteousness', 'preach the word'),
  P('The Grace of God Hath Appeared', 'Titus', 2, 11, 15, 'grace of god that bringeth salvation', 'blessed hope'),
  P('Christ the Final Word', 'Hebrews', 1, 1, 14, 'god who at sundry times', 'express image of his person'),
  P('The Word Is Quick and Powerful', 'Hebrews', 4, 9, 16, 'word of god is quick and powerful', 'throne of grace', 'sharper than any twoedged sword', 'touched with the feeling of our infirmities'),
  P('Melchisedec', 'Hebrews', 7, 1, 28, 'melchisedec', 'melchizedek', 'order of melchisedec'),
  P('The Faith Chapter', 'Hebrews', 11, 1, 40, 'faith chapter', 'hall of faith', 'faith is the substance of things hoped for', 'by faith'),
  P('The Race Set Before Us', 'Hebrews', 12, 1, 13, 'cloud of witnesses', 'run with patience the race', 'author and finisher of our faith', 'whom the lord loveth he chasteneth'),
  P('Jesus Christ the Same Yesterday, Today, and Forever', 'Hebrews', 13, 1, 8, 'same yesterday and to day and for ever', 'entertained angels unawares', 'i will never leave thee'),
  P('Count It All Joy', 'James', 1, 1, 18, 'count it all joy', 'trying of your faith worketh patience', 'if any of you lack wisdom', 'every good gift'),
  P('Doers of the Word', 'James', 1, 19, 27, 'doers of the word', 'swift to hear slow to speak', 'pure religion'),
  P('Faith Without Works', 'James', 2, 14, 26, 'faith without works is dead'),
  P('The Tongue', 'James', 3, 1, 12, 'tongue', 'the tongue is a fire', 'bridle'),
  P('Draw Nigh to God', 'James', 4, 1, 10, 'draw nigh to god', 'resist the devil', 'humble yourselves'),
  P('The Prayer of Faith', 'James', 5, 13, 20, 'effectual fervent prayer', 'prayer of faith shall save the sick', 'anointing with oil', 'elijah prayed'),
  P('A Lively Hope', '1 Peter', 1, 3, 12, 'lively hope', 'incorruptible inheritance', 'trial of your faith'),
  P('A Royal Priesthood', '1 Peter', 2, 1, 12, 'chosen generation', 'royal priesthood', 'peculiar people', 'lively stones', 'sincere milk of the word'),
  P('Casting All Your Care', '1 Peter', 5, 5, 11, 'casting all your care upon him', 'roaring lion', 'be sober be vigilant'),
  P('Make Your Calling and Election Sure', '2 Peter', 1, 1, 11, 'add to your faith virtue', 'precious promises', 'calling and election sure'),
  P('The Day of the Lord', '2 Peter', 3, 1, 13, 'thief in the night', 'thousand years as one day', 'not willing that any should perish', 'elements shall melt'),
  P('Walk in the Light', '1 John', 1, 1, 10, 'walk in the light', 'if we confess our sins', 'fellowship one with another'),
  P('Love Not the World', '1 John', 2, 15, 17, 'love not the world', 'lust of the flesh', 'pride of life'),
  P('God Is Love', '1 John', 4, 7, 21, 'god is love', 'perfect love casteth out fear', 'beloved let us love one another', 'we love him because he first loved us'),
  P('Beloved, Thou Prosper', '3 John', 1, 1, 4, 'prosper and be in health', 'no greater joy'),
  P('Now unto Him That Is Able to Keep You', 'Jude', 1, 17, 25, 'keep you from falling', 'contend for the faith', 'doxology'),
  // --- Revelation
  P('The Alpha and Omega', 'Revelation', 1, 1, 20, 'alpha and omega', 'i am he that liveth and was dead', 'patmos'),
  P('Letters to the Seven Churches', 'Revelation', 2, 1, 29, 'seven churches', 'ephesus smyrna pergamos thyatira', 'first love'),
  P('Laodicea: Behold, I Stand at the Door', 'Revelation', 3, 14, 22, 'lukewarm', 'laodicea', 'i stand at the door and knock'),
  P('The Throne in Heaven', 'Revelation', 4, 1, 11, 'throne room', 'holy holy holy lord god almighty', 'four beasts', 'twenty four elders'),
  P('Worthy Is the Lamb', 'Revelation', 5, 1, 14, 'worthy is the lamb', 'lion of the tribe of juda', 'sealed book'),
  P('The Great Multitude', 'Revelation', 7, 9, 17, 'great multitude which no man could number', 'washed their robes', 'wipe away all tears'),
  P('The Marriage Supper of the Lamb', 'Revelation', 19, 1, 10, 'marriage supper of the lamb', 'alleluia', 'bride hath made herself ready'),
  P('The Rider on the White Horse', 'Revelation', 19, 11, 21, 'king of kings and lord of lords', 'white horse', 'faithful and true'),
  P('The Great White Throne', 'Revelation', 20, 11, 15, 'great white throne', 'book of life', 'lake of fire'),
  P('A New Heaven and a New Earth', 'Revelation', 21, 1, 8, 'new heaven and a new earth', 'new jerusalem', 'no more death', 'behold i make all things new'),
  P('The River of Life', 'Revelation', 22, 1, 21, 'river of water of life', 'tree of life', 'even so come lord jesus', 'behold i come quickly'),
]

interface Indexed { p: Passage; segs: string[][] }
// Title and each alias are separate segments: a phrase run can't bridge "lost sheep" +
// "lost coin" into a 3-word match.
const INDEX: Indexed[] = PASSAGES.map((p) => ({
  p,
  segs: [p.title, ...p.aliases].map((s) => norm(s).split(' ').filter(Boolean)),
}))

/** Every query word must match (prefix/fuzzy, same rules as verse search); only the nearest
 * dist tier survives — a closer match hides fuzzier ones: 'zacch' is Zacchaeus, not
 * Gethsemane via 'watch'. Then order by phrase run ↓, matched weight ↓, dist ↑ (a no-op
 * within the surviving tier, kept for clarity), title length ↑, then canonical ↑ so the
 * table's order never leaks into the result. */
export function matchPassages(q: string, limit = 3): Passage[] {
  const { tokens } = parseVerseQuery(q)
  if (!tokens.length) return []
  const hits = INDEX.map(({ p, segs }) => ({ p, s: textSignals(segs, tokens) })).filter(
    (x) => x.s.matched === tokens.length,
  )
  const minDist = hits.reduce((m, x) => Math.min(m, x.s.dist), Infinity)
  return hits
    .filter((x) => x.s.dist === minDist)
    .sort((a, b) => {
      if (b.s.phrase !== a.s.phrase) return b.s.phrase - a.s.phrase
      if (b.s.covWeight !== a.s.covWeight) return b.s.covWeight - a.s.covWeight
      if (a.s.dist !== b.s.dist) return a.s.dist - b.s.dist
      if (a.p.title.length !== b.p.title.length) return a.p.title.length - b.p.title.length
      const bi = canonicalBookIndex(a.p.book) - canonicalBookIndex(b.p.book)
      if (bi) return bi
      if (a.p.ch !== b.p.ch) return a.p.ch - b.p.ch
      return a.p.from - b.p.from
    })
    .slice(0, limit)
    .map((x) => x.p)
}
